### ISSUE TITLE
Support for extensions of Command

### ISSUE THREAD

**Issue by edelmanjm** [flamingchickens1540/ROOSTER#3]
As is, ChickenCommand doesn't contain the abilities of many of the [specialized command classes.](http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/command/package-frame.html) This would be nice to have.

**Comment by edelmanjm** [comment]
@RobinsonZ That's not how that works. You wait for the PR to be merged into master, at which point the issue auto-closes.

**Comment by RobinsonZ** [comment]
Ah, ok–I figured since we're kind of using `gradle-integration` as a master branch it might be good. That said we _really_ should think about merging the branch even though power management isn't tested–it's in master anyway, we can create a new branch and just not make a release until we've tested power management.

**Comment by edelmanjm** [comment]
@RobinsonZ I'm going to test it tomorrow anyways, just wait a day.

**Comment by RobinsonZ** [comment]
Closing since evidently it didn't auto-close when `gradle-integration` was merged.
