### ISSUE TITLE
ChickenSubsystem doesn't accept ChickenControllers

### ISSUE THREAD

**Issue by nwsnate** [flamingchickens1540/ROOSTER#37]
@edelmanjm `ChickenSubsystem` only works with `ChickenTalons`.

**Comment by RobinsonZ** [comment]
Wait, I realize there's a bit of a larger issue because Victors don't have the current limiting feature. I'm going to implement a hacky fix by doing a type check and only current limiting if it's a talon, but we definitely want to implement a slightly better structure or maybe just drop `ChickenSubsystem` entirely.

**Comment by edelmanjm** [comment]
@RobinsonZ ¯\_(ツ)_/¯ I intentionally made it only accept ChickenTalons with the intention that in it's current state the best way to do things is just to use it as a power-management-only type of deal. Your solution works, but if you ever need to reference specific motors, ChickenSubsystem still fails you. Overall there just need sot be a better solution.

**Comment by edelmanjm** [comment]
Closed by #43, except not really, see #45.
