### ISSUE TITLE
Victor SPXs don't actually support getting current telemetry

### ISSUE THREAD

**Issue by edelmanjm** [flamingchickens1540/ROOSTER#45]
Why does the .getOutputCurrent() method seem to be written? Unclear.

Temporarily stuff can be hacked together to get the current data by grabbing it from the PDP assuming the wiring is all nice, but that's dumb.

**Comment by edelmanjm** [comment]
Actually the more that I think about this, it isn't *necessarily* an issue; you just limit them equally but they get ignored when actually grabbing the current data. The only real danger is in thinking that they do anything, such as in an all-Victor subsystem.

**Comment by RobinsonZ** [comment]
All-victor subsystems are a non-negligible thing though. Our intake and tape measure don't draw much power, but aside from current telemetry, there is literally no reason we need an SRX on the winch; that could have been a significant power-drawing mechanism with solely victors.

**Comment by edelmanjm** [comment]
¯\\\_(ツ)_/¯ Override getCurrent then and manually write your own bit? I don't see a clean solution.

**Comment by edelmanjm** [comment]
Although I guess there is the issue that if getCurrent returns 0 you'll get a divide by zero... should probably fix that.

**Comment by RobinsonZ** [comment]
Just because you can get the current doesn't mean you can limit the power (victors with hacky PDP telemetry). Perhaps split the `PowerManageable` interface into both a `CurrentUser` and a `Limitable` interface, to separate telemetry and limiting functions? That would also be a good thing because the manager can take into account that it has X amount of unchangeable current draw and X amount of current draw that it can reduce.

**Comment by edelmanjm** [comment]
You can limit the power just fine now, it uses voltage. I do like splitting it up tho.

**Comment by edelmanjm** [comment]
Resolved by b51d5323fb87413a161b66cffb2d27eed68c3843, with ongoing improvements and bugfixes in that branch.
